name: Linux Lab Sync
on:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Delta Mirror to Codeberg
        run: |
          # Increase buffer for safety
          git config --global http.postBuffer 524288000
          
          # Clone only the latest to keep the runner fast
          git clone --mirror --depth 50 https://github.com/torvalds/linux.git kernel.git
          cd kernel.git

          # Force push 
          git push --force https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/spiritedcaveman/linux-lab.git
