name: Full Kernel Mirror
on:
  workflow_dispatch: 

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Heavy Duty Mirror
        run: |
          # 1. Increase buffers to the max
          git config --global http.postBuffer 1048576000
          git config --global core.compression 9

          #
          git clone --mirror https://github.com/torvalds/linux.git kernel.git
          cd kernel.git

          # 3. Add Codeberg
          git remote add codeberg https://${{ secrets.CODEBERG_TOKEN }}@codeberg.org/spiritedcaveman/linux-lab.git

          
          git push codeberg main
          git push --tags codeberg
          git push --mirror codeberg
